---
name: Selenium Webdriver CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up .Net
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run tests
      run: |
        echo "Running TestProject1"
        dotnet test TestProject1/TestProject1.csproj --verbosity normal
    - name: Run tests
      run: |
        echo "Running TestProject2"
        dotnet test TestProject2/TestProject2.csproj --verbosity normal
    - name: Run tests
      run: |
        echo "Running TestProject3"
        dotnet test TestProject3/TestProject3.csproj --verbosity normal
